FROM nginx:1.23.2-alpine
COPY ./dist/http-get-app/ /usr/share/nginx/html
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./nginx.local.conf /etc/nginx/conf.d
RUN mv /etc/nginx/conf.d/nginx.local.conf  /etc/nginx/conf.d/nginx.conf
